import type { Locale } from "@/lib/i18n";

const it = {
  "compare.title": "Trova il tuo preferito.", "compare.label": "Confronto prodotti",
  "compare.intro": "Due scelte, tutti i dettagli. Confronta i prodotti e scopri il prezzo più basso tra i due.",
  "compare.add": "Confronta", "compare.selected": "Nel confronto", "compare.addLabel": "Confronta {name}",
  "compare.removeLabel": "Rimuovi {name} dal confronto", "compare.countLabel": "Confronto prodotti: {count} selezionati su 2",
  "compare.hint": "Indeciso? Seleziona fino a 2 prodotti per confrontarli.",
  "compare.limit": "Puoi confrontare al massimo 2 prodotti. Rimuovine uno per aggiungerne un altro.",
  "compare.added": "Prodotto aggiunto al confronto.", "compare.removed": "Prodotto rimosso dal confronto.", "compare.cleared": "Confronto svuotato.",
  "compare.open": "Confronta i prodotti", "compare.clear": "Svuota", "compare.choose": "Scegli un prodotto", "compare.chooseSecond": "Scegli il secondo prodotto",
  "compare.empty": "La scelta comincia qui.", "compare.emptyCopy": "Nel catalogo, premi Confronta sui due prodotti che ti interessano. Li ritroverai qui, uno accanto all’altro.",
  "compare.browse": "Esplora il catalogo", "compare.back": "Continua a scegliere", "compare.remove": "Rimuovi",
  "compare.loading": "Caricamento dei prezzi e dei dettagli…", "compare.loadError": "Non riusciamo a caricare il confronto. Riprova tra poco.", "compare.retry": "Riprova",
  "compare.invalid": "Seleziona al massimo 2 prodotti validi.", "compare.unavailable": "Prodotto non più disponibile nel catalogo",
  "compare.lowest": "Prezzo più basso", "compare.saving": "{amount} in meno", "compare.equal": "Stesso prezzo per entrambi",
  "compare.noWinner": "Il prezzo più basso viene evidenziato quando entrambi i prodotti sono disponibili nella stessa valuta.",
  "compare.priceNote": "Prezzi dei prodotti prima di eventuali coupon. Con taglie a prezzi diversi, il confronto considera la variante disponibile meno cara.",
  "compare.price": "Prezzo", "compare.from": "da {price}", "compare.brand": "Brand", "compare.category": "Categoria", "compare.sizes": "Taglie disponibili", "compare.availability": "Disponibilità",
  "compare.inStock": "Disponibile", "compare.soldOut": "Esaurito", "compare.notSpecified": "Non indicato", "compare.view": "Vedi prodotto",
} as const;

export const comparisonCopy: Record<Locale, Record<keyof typeof it, string>> = {
  it,
  en: {
    "compare.title": "Find your favourite.", "compare.label": "Product comparison", "compare.intro": "Two choices, every detail. Compare products and find the lower price of the two.",
    "compare.add": "Compare", "compare.selected": "Selected", "compare.addLabel": "Compare {name}", "compare.removeLabel": "Remove {name} from comparison", "compare.countLabel": "Product comparison: {count} of 2 selected",
    "compare.hint": "Undecided? Select up to 2 products to compare.", "compare.limit": "You can compare up to 2 products. Remove one to add another.",
    "compare.added": "Product added to comparison.", "compare.removed": "Product removed from comparison.", "compare.cleared": "Comparison cleared.",
    "compare.open": "Compare products", "compare.clear": "Clear", "compare.choose": "Choose a product", "compare.chooseSecond": "Choose a second product",
    "compare.empty": "Your choice starts here.", "compare.emptyCopy": "In the catalogue, select Compare on two products you like. You will find them here, side by side.",
    "compare.browse": "Explore the catalogue", "compare.back": "Keep browsing", "compare.remove": "Remove", "compare.loading": "Loading prices and details…", "compare.loadError": "We could not load the comparison. Please try again shortly.", "compare.retry": "Try again",
    "compare.invalid": "Select up to 2 valid products.", "compare.unavailable": "Product no longer available in the catalogue", "compare.lowest": "Lower price", "compare.saving": "{amount} less", "compare.equal": "Same price for both",
    "compare.noWinner": "The lower price is highlighted when both products are available in the same currency.", "compare.priceNote": "Product prices before any coupons. When sizes have different prices, we compare the cheapest available variant.",
    "compare.price": "Price", "compare.from": "from {price}", "compare.brand": "Brand", "compare.category": "Category", "compare.sizes": "Available sizes", "compare.availability": "Availability", "compare.inStock": "In stock", "compare.soldOut": "Sold out", "compare.notSpecified": "Not specified", "compare.view": "View product",
  },
  fr: {
    "compare.title": "Trouvez votre préféré.", "compare.label": "Comparaison de produits", "compare.intro": "Deux choix, tous les détails. Comparez les produits et découvrez le prix le plus bas des deux.",
    "compare.add": "Comparer", "compare.selected": "Sélectionné", "compare.addLabel": "Comparer {name}", "compare.removeLabel": "Retirer {name} de la comparaison", "compare.countLabel": "Comparaison : {count} produits sur 2 sélectionnés",
    "compare.hint": "Vous hésitez ? Sélectionnez jusqu’à 2 produits à comparer.", "compare.limit": "Vous pouvez comparer 2 produits maximum. Retirez-en un pour en ajouter un autre.",
    "compare.added": "Produit ajouté à la comparaison.", "compare.removed": "Produit retiré de la comparaison.", "compare.cleared": "Comparaison vidée.",
    "compare.open": "Comparer les produits", "compare.clear": "Vider", "compare.choose": "Choisir un produit", "compare.chooseSecond": "Choisir le deuxième produit",
    "compare.empty": "Votre choix commence ici.", "compare.emptyCopy": "Dans le catalogue, cliquez sur Comparer pour les deux produits qui vous intéressent. Retrouvez-les ici, côte à côte.",
    "compare.browse": "Explorer le catalogue", "compare.back": "Continuer à choisir", "compare.remove": "Retirer", "compare.loading": "Chargement des prix et des détails…", "compare.loadError": "Impossible de charger la comparaison. Réessayez dans un instant.", "compare.retry": "Réessayer",
    "compare.invalid": "Sélectionnez au maximum 2 produits valides.", "compare.unavailable": "Produit indisponible dans le catalogue", "compare.lowest": "Prix le plus bas", "compare.saving": "{amount} de moins", "compare.equal": "Même prix pour les deux",
    "compare.noWinner": "Le prix le plus bas est indiqué lorsque les deux produits sont disponibles dans la même devise.", "compare.priceNote": "Prix des produits avant tout code de réduction. Si les prix varient selon la taille, nous comparons la variante disponible la moins chère.",
    "compare.price": "Prix", "compare.from": "à partir de {price}", "compare.brand": "Marque", "compare.category": "Catégorie", "compare.sizes": "Tailles disponibles", "compare.availability": "Disponibilité", "compare.inStock": "Disponible", "compare.soldOut": "Épuisé", "compare.notSpecified": "Non indiqué", "compare.view": "Voir le produit",
  },
  es: {
    "compare.title": "Encuentra tu favorito.", "compare.label": "Comparación de productos", "compare.intro": "Dos opciones, todos los detalles. Compara los productos y descubre el precio más bajo de los dos.",
    "compare.add": "Comparar", "compare.selected": "Seleccionado", "compare.addLabel": "Comparar {name}", "compare.removeLabel": "Quitar {name} de la comparación", "compare.countLabel": "Comparación: {count} de 2 productos seleccionados",
    "compare.hint": "¿No te decides? Selecciona hasta 2 productos para compararlos.", "compare.limit": "Puedes comparar un máximo de 2 productos. Quita uno para añadir otro.",
    "compare.added": "Producto añadido a la comparación.", "compare.removed": "Producto eliminado de la comparación.", "compare.cleared": "Comparación vaciada.",
    "compare.open": "Comparar productos", "compare.clear": "Vaciar", "compare.choose": "Elige un producto", "compare.chooseSecond": "Elige el segundo producto",
    "compare.empty": "Tu elección empieza aquí.", "compare.emptyCopy": "En el catálogo, pulsa Comparar en los dos productos que te interesan. Los encontrarás aquí, uno al lado del otro.",
    "compare.browse": "Explorar el catálogo", "compare.back": "Seguir eligiendo", "compare.remove": "Quitar", "compare.loading": "Cargando precios y detalles…", "compare.loadError": "No se ha podido cargar la comparación. Inténtalo de nuevo en un momento.", "compare.retry": "Reintentar",
    "compare.invalid": "Selecciona un máximo de 2 productos válidos.", "compare.unavailable": "Producto ya no disponible en el catálogo", "compare.lowest": "Precio más bajo", "compare.saving": "{amount} menos", "compare.equal": "Mismo precio para ambos",
    "compare.noWinner": "Se destaca el precio más bajo cuando ambos productos están disponibles en la misma moneda.", "compare.priceNote": "Precios antes de aplicar cupones. Si los precios varían según la talla, comparamos la variante disponible más barata.",
    "compare.price": "Precio", "compare.from": "desde {price}", "compare.brand": "Marca", "compare.category": "Categoría", "compare.sizes": "Tallas disponibles", "compare.availability": "Disponibilidad", "compare.inStock": "Disponible", "compare.soldOut": "Agotado", "compare.notSpecified": "No indicado", "compare.view": "Ver producto",
  },
  de: {
    "compare.title": "Finde deinen Favoriten.", "compare.label": "Produktvergleich", "compare.intro": "Zwei Optionen, alle Details. Vergleiche die Produkte und entdecke den niedrigeren Preis der beiden.",
    "compare.add": "Vergleichen", "compare.selected": "Ausgewählt", "compare.addLabel": "{name} vergleichen", "compare.removeLabel": "{name} aus dem Vergleich entfernen", "compare.countLabel": "Produktvergleich: {count} von 2 ausgewählt",
    "compare.hint": "Unentschlossen? Wähle bis zu 2 Produkte zum Vergleichen.", "compare.limit": "Du kannst höchstens 2 Produkte vergleichen. Entferne eines, um ein anderes hinzuzufügen.",
    "compare.added": "Produkt zum Vergleich hinzugefügt.", "compare.removed": "Produkt aus dem Vergleich entfernt.", "compare.cleared": "Vergleich geleert.",
    "compare.open": "Produkte vergleichen", "compare.clear": "Leeren", "compare.choose": "Produkt auswählen", "compare.chooseSecond": "Zweites Produkt auswählen",
    "compare.empty": "Deine Auswahl beginnt hier.", "compare.emptyCopy": "Wähle im Katalog bei zwei Produkten Vergleichen aus. Hier siehst du sie dann nebeneinander.",
    "compare.browse": "Katalog entdecken", "compare.back": "Weiter stöbern", "compare.remove": "Entfernen", "compare.loading": "Preise und Details werden geladen…", "compare.loadError": "Der Vergleich konnte nicht geladen werden. Bitte versuche es gleich erneut.", "compare.retry": "Erneut versuchen",
    "compare.invalid": "Wähle höchstens 2 gültige Produkte aus.", "compare.unavailable": "Produkt nicht mehr im Katalog verfügbar", "compare.lowest": "Niedrigerer Preis", "compare.saving": "{amount} weniger", "compare.equal": "Gleicher Preis für beide",
    "compare.noWinner": "Der niedrigere Preis wird hervorgehoben, wenn beide Produkte in derselben Währung verfügbar sind.", "compare.priceNote": "Produktpreise vor Gutscheinen. Bei unterschiedlichen Größenpreisen vergleichen wir die günstigste verfügbare Variante.",
    "compare.price": "Preis", "compare.from": "ab {price}", "compare.brand": "Marke", "compare.category": "Kategorie", "compare.sizes": "Verfügbare Größen", "compare.availability": "Verfügbarkeit", "compare.inStock": "Verfügbar", "compare.soldOut": "Ausverkauft", "compare.notSpecified": "Nicht angegeben", "compare.view": "Produkt ansehen",
  },
};
