import type { Locale } from "@/lib/i18n";

export const newsletterCopy: Record<Locale, { consent: string; privacy: string; busy: string; success: string; error: string; invalid: string }> = {
  it: { consent: "Acconsento a ricevere via email novità e offerte di LCS. Posso revocare il consenso scrivendo a info@ekobit.it.", privacy: "Leggi l'informativa privacy", busy: "Registrazione…", success: "Iscrizione registrata. Grazie, sei nella private list di LCS.", error: "Iscrizione non riuscita. Riprova tra poco.", invalid: "Inserisci un'email valida e conferma il consenso." },
  en: { consent: "I agree to receive LCS news and offers by email. I can withdraw consent by writing to info@ekobit.it.", privacy: "Read the privacy notice", busy: "Subscribing…", success: "Subscription saved. Thank you for joining the LCS private list.", error: "Subscription failed. Please try again shortly.", invalid: "Enter a valid email and confirm your consent." },
  fr: { consent: "J'accepte de recevoir les nouveautés et offres LCS par e-mail. Je peux retirer mon consentement à info@ekobit.it.", privacy: "Lire la politique de confidentialité", busy: "Inscription…", success: "Inscription enregistrée. Merci de rejoindre la private list LCS.", error: "Échec de l'inscription. Réessayez dans un instant.", invalid: "Saisissez un e-mail valide et confirmez votre consentement." },
  es: { consent: "Acepto recibir novedades y ofertas de LCS por email. Puedo retirar mi consentimiento escribiendo a info@ekobit.it.", privacy: "Leer la política de privacidad", busy: "Registrando…", success: "Inscripción guardada. Gracias por unirte a la private list de LCS.", error: "No se pudo completar la inscripción. Inténtalo de nuevo.", invalid: "Introduce un email válido y confirma tu consentimiento." },
  de: { consent: "Ich möchte Neuigkeiten und Angebote von LCS per E-Mail erhalten. Ich kann meine Einwilligung unter info@ekobit.it widerrufen.", privacy: "Datenschutzhinweise lesen", busy: "Anmeldung…", success: "Anmeldung gespeichert. Vielen Dank für Ihr Interesse an der LCS Private List.", error: "Anmeldung fehlgeschlagen. Bitte versuchen Sie es später erneut.", invalid: "Geben Sie eine gültige E-Mail-Adresse ein und bestätigen Sie Ihre Einwilligung." },
};
