import {
  catalogCategories,
  type CatalogBrand,
  type CatalogCategoryName,
} from "./catalog";

export type PlaceholderProduct = {
  id: string;
  categoryName: CatalogCategoryName;
  categoryId: string;
  name: string;
  slug: string;
  sku: string;
  price: number;
  currency: "EUR";
  imageUrl: string;
  brand: CatalogBrand;
  shortDescription: string;
  description: string;
};

const categoryIds = Object.fromEntries(
  catalogCategories.map((category) => [category.name, category.id]),
) as Record<CatalogCategoryName, string>;

export const placeholderProducts: PlaceholderProduct[] = [
  {
    id: "21000000-0000-4000-8000-000000000001",
    categoryName: "T-shirt",
    categoryId: categoryIds["T-shirt"],
    name: "T-shirt Christian Dior Couture dalla vestibilità comoda",
    slug: "dior-t-shirt-christian-dior-couture",
    sku: "DIOR-TSH-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/dior-tshirt-christian-dior-couture.png",
    brand: "Dior",
    shortDescription: "T-shirt girocollo con firma Christian Dior Couture sul petto.",
    description: "Modello dalla vestibilità comoda, proposto nelle varianti bianca e nera. Il girocollo essenziale e la firma Christian Dior Couture sul davanti definiscono un capo quotidiano facile da abbinare. Composizione, taglie e condizioni saranno verificate prima della pubblicazione definitiva.",
  },
  {
    id: "21000000-0000-4000-8000-000000000002",
    categoryName: "Cinture",
    categoryId: categoryIds.Cinture,
    name: "Cintura in pelle avorio con fibbia rotonda Interlocking G",
    slug: "gucci-cintura-interlocking-g-in-pelle-avorio",
    sku: "GUCCI-BEL-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/gucci-cintura-interlocking-g.png",
    brand: "Gucci",
    shortDescription: "Cintura color avorio con fibbia rotonda Interlocking G.",
    description: "Una cintura in tonalità avorio dalla linea pulita, completata da una fibbia rotonda con dettaglio Interlocking G. Pensata per essere indossata in vita o sui fianchi. Materiali, misura e finiture esatte saranno verificati sul prodotto prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000003",
    categoryName: "Felpe e cardigan",
    categoryId: categoryIds["Felpe e cardigan"],
    name: "Cardigan reversibile con cappuccio Dior Oblique",
    slug: "dior-cardigan-reversibile-cappuccio-oblique",
    sku: "DIOR-CAR-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/dior-cardigan-oblique.png",
    brand: "Dior",
    shortDescription: "Cardigan grigio reversibile con cappuccio e motivo Dior Oblique.",
    description: "Cardigan con cappuccio, chiusura frontale con zip e finiture a costine. Il modello reversibile alterna un lato grigio essenziale e un lato con motivo Dior Oblique all-over. Composizione, taglie e condizioni saranno confermate prima della pubblicazione definitiva.",
  },
  {
    id: "21000000-0000-4000-8000-000000000004",
    categoryName: "Pantaloni",
    categoryId: categoryIds.Pantaloni,
    name: "Jeans cargo Dior in twill di cotone blu",
    slug: "dior-jeans-cargo-twill-cotone-blu",
    sku: "DIOR-PAN-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/dior-cargo-jeans-blue.png",
    brand: "Dior",
    shortDescription: "Jeans cargo blu dalla gamba ampia con tasche applicate laterali.",
    description: "Un modello ispirato al guardaroba utility, realizzato in denim blu con passanti in vita e ampie tasche cargo sui lati. La linea è dritta e rilassata. Composizione, taglia, codice articolo e condizioni saranno verificati direttamente sul capo prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000005",
    categoryName: "Camicie e polo",
    categoryId: categoryIds["Camicie e polo"],
    name: "Camicia bowling Gucci in seta jacquard GG nera",
    slug: "gucci-camicia-bowling-seta-jacquard-gg-nera",
    sku: "GUCCI-CAM-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/gucci-gg-silk-jacquard-bowling-shirt-black.png",
    brand: "Gucci",
    shortDescription: "Camicia nera a maniche corte con motivo GG jacquard all-over.",
    description: "Camicia bowling con colletto aperto, chiusura frontale con bottoni e tasca applicata sul petto. Il motivo GG tono su tono attraversa l'intera superficie. Materiale, taglia, riferimento e condizioni del capo fotografato saranno confermati prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000006",
    categoryName: "Camicie e polo",
    categoryId: categoryIds["Camicie e polo"],
    name: "Camicia bowling Gucci in canvas GG beige",
    slug: "gucci-camicia-bowling-canvas-gg-beige",
    sku: "GUCCI-CAM-002",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/gucci-gg-canvas-bowling-shirt-beige.png",
    brand: "Gucci",
    shortDescription: "Camicia beige a maniche corte con monogramma GG blu all-over.",
    description: "Camicia dalla costruzione bowling, con colletto aperto, bottoni frontali e motivo GG ripetuto in contrasto. La linea appare morbida e adatta alla stagione calda. Composizione, taglia, codice esatto e condizioni saranno verificati sul prodotto.",
  },
  {
    id: "21000000-0000-4000-8000-000000000007",
    categoryName: "T-shirt",
    categoryId: categoryIds["T-shirt"],
    name: "T-shirt Gucci in jersey con ricamo logo",
    slug: "gucci-t-shirt-jersey-ricamo-logo",
    sku: "GUCCI-TSH-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/gucci-logo-embroidered-tshirt.png",
    brand: "Gucci",
    shortDescription: "T-shirt girocollo con grande ricamo Gucci nelle varianti bianca e nera.",
    description: "T-shirt a maniche corte dalla linea essenziale, caratterizzata dal ricamo Gucci frontale nei toni rosso e verde. La foto mostra le varianti bianca e nera. Composizione, vestibilità, taglie disponibili e autenticità saranno verificate prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000008",
    categoryName: "T-shirt",
    categoryId: categoryIds["T-shirt"],
    name: "T-shirt Balenciaga con logo distorto",
    slug: "balenciaga-t-shirt-logo-distorto-nera",
    sku: "BAL-TSH-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/balenciaga-distorted-logo-tshirt-black.png",
    brand: "Balenciaga",
    shortDescription: "T-shirt nera a maniche corte con grafica Balenciaga distorta.",
    description: "T-shirt girocollo nera con stampa frontale grigia dall'effetto mosso e distorto. La silhouette appare ampia e rilassata. Tessuto, taglia, codice modello, condizioni e autenticità saranno confermati direttamente sul capo.",
  },
  {
    id: "21000000-0000-4000-8000-000000000009",
    categoryName: "Pantaloni",
    categoryId: categoryIds.Pantaloni,
    name: "Pantaloni tuta Balenciaga Loop Sports Icon",
    slug: "balenciaga-loop-sports-icon-track-pants",
    sku: "BAL-PAN-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/balenciaga-loop-sports-icon-track-pants.png",
    brand: "Balenciaga",
    shortDescription: "Pantaloni sportivi blu e neri con pannelli e bande laterali a contrasto.",
    description: "Pantaloni da tuta in tessuto tecnico con vita elasticizzata e coulisse, costruzione a pannelli e gamba ampia. Le bande laterali chiare e il ricamo Loop Sports Icon completano il modello. Taglia, composizione, codice e condizioni saranno verificati prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000010",
    categoryName: "Felpe e cardigan",
    categoryId: categoryIds["Felpe e cardigan"],
    name: "Felpa Balenciaga Flipped Uni con zip",
    slug: "balenciaga-flipped-uni-felpa-zip-nera",
    sku: "BAL-FEL-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/balenciaga-flipped-uni-zip-hoodie.png",
    brand: "Balenciaga",
    shortDescription: "Felpa nera con cappuccio, zip e logo Balenciaga capovolto sul petto.",
    description: "Felpa con cappuccio dalla vestibilità rilassata, chiusura frontale con zip e due tasche applicate. Il piccolo logo ricamato con effetto capovolto firma il davanti. Composizione, taglia, riferimento e condizioni saranno controllati sul capo.",
  },
  {
    id: "21000000-0000-4000-8000-000000000011",
    categoryName: "Giacche",
    categoryId: categoryIds.Giacche,
    name: "Giacca tuta Balenciaga Soccer nera",
    slug: "balenciaga-soccer-tracksuit-jacket-nera",
    sku: "BAL-GIA-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/balenciaga-soccer-tracksuit-jacket.png",
    brand: "Balenciaga",
    shortDescription: "Giacca sportiva nera con collo alto, profili riflettenti e stemma ricamato.",
    description: "Giacca Soccer con collo alto, zip frontale e profili a contrasto. Lo stemma con corona d'alloro e le grafiche Balenciaga sul davanti richiamano l'abbigliamento da squadra. Taglia, composizione e condizioni saranno verificate prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000012",
    categoryName: "Camicie e polo",
    categoryId: categoryIds["Camicie e polo"],
    name: "Polo Burberry con motivo Icon Stripe",
    slug: "burberry-polo-icon-stripe",
    sku: "BUR-POL-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/burberry-icon-stripe-polo.png",
    brand: "Burberry",
    shortDescription: "Polo a maniche corte con dettaglio Icon Stripe, bianca o nera.",
    description: "Polo con colletto classico e abbottonatura frontale, caratterizzata dal motivo a righe nei toni beige, rosso, bianco e nero. La foto mostra due varianti colore. Materiale, vestibilità, taglie e riferimento esatto saranno verificati sul capo.",
  },
  {
    id: "21000000-0000-4000-8000-000000000013",
    categoryName: "Giacche",
    categoryId: categoryIds.Giacche,
    name: "Giacca Burberry con cappuccio Vintage Check",
    slug: "burberry-giacca-cappuccio-vintage-check",
    sku: "BUR-GIA-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/burberry-check-hooded-jacket.png",
    brand: "Burberry",
    shortDescription: "Giacca leggera con cappuccio e motivo Vintage Check color beige archivio.",
    description: "Giacca con cappuccio e chiusura frontale con zip, costruita attorno al riconoscibile motivo Vintage Check. Il taglio è lineare e pensato come strato leggero. Composizione, eventuale reversibilità, taglia e condizioni saranno confermate prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000014",
    categoryName: "Cinture",
    categoryId: categoryIds.Cinture,
    name: "Cintura Burberry reversibile in pelle con fibbia TB",
    slug: "burberry-cintura-reversibile-pelle-fibbia-tb",
    sku: "BUR-BEL-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/burberry-tb-belt.png",
    brand: "Burberry",
    shortDescription: "Cintura nera in pelle con fibbia Thomas Burberry Monogram dorata.",
    description: "Cintura in pelle con fibbia TB in metallo color oro e costruzione reversibile. La linea pulita la rende adatta sia a pantaloni formali sia a denim. Misura, larghezza, materiali e condizioni saranno verificati direttamente sul prodotto.",
  },
  {
    id: "21000000-0000-4000-8000-000000000015",
    categoryName: "Giacche",
    categoryId: categoryIds.Giacche,
    name: "Camicia-giacca Prada Re-Nylon nera",
    slug: "prada-camicia-giacca-re-nylon-nera",
    sku: "PRADA-GIA-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/prada-re-nylon-shirt-black.png",
    brand: "Prada",
    shortDescription: "Camicia-giacca nera con bottoni a pressione e logo triangolare smaltato.",
    description: "Camicia-giacca nera in Re-Nylon con colletto classico, chiusura frontale a pressione e tasche integrate. Il logo triangolare smaltato firma il taschino sul petto. Taglia, vestibilità, imbottitura e riferimento esatto saranno verificati direttamente sul capo.",
  },
  {
    id: "21000000-0000-4000-8000-000000000016",
    categoryName: "Cinture",
    categoryId: categoryIds.Cinture,
    name: "Cintura Prada in pelle Saffiano con fibbia triangolare",
    slug: "prada-cintura-saffiano-fibbia-triangolare",
    sku: "PRADA-BEL-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/prada-saffiano-triangle-belt-black.png",
    brand: "Prada",
    shortDescription: "Cintura nera in pelle Saffiano con fibbia triangolare in metallo e smalto.",
    description: "Cintura in pelle Saffiano nera completata da una fibbia triangolare con finitura metallica e dettaglio smaltato. Il design richiama il logo geometrico della maison. Misura, larghezza, finitura e condizioni saranno confermate sul prodotto.",
  },
  {
    id: "21000000-0000-4000-8000-000000000017",
    categoryName: "Giacche",
    categoryId: categoryIds.Giacche,
    name: "Giacca Prada Re-Nylon con cappuccio",
    slug: "prada-giacca-re-nylon-cappuccio-nera",
    sku: "PRADA-GIA-002",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/prada-re-nylon-hooded-jacket-black.png",
    brand: "Prada",
    shortDescription: "Giacca nera con cappuccio, zip frontale e logo triangolare smaltato.",
    description: "Giacca leggera nera in Re-Nylon con cappuccio, chiusura frontale con zip e taschino sul petto. Il logo triangolare smaltato completa il davanti. Composizione, vestibilità, taglia e codice esatto saranno verificati prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000018",
    categoryName: "Pantaloni",
    categoryId: categoryIds.Pantaloni,
    name: "Jeans Prada a gamba ampia con effetto vernice",
    slug: "prada-jeans-gamba-ampia-effetto-vernice",
    sku: "PRADA-PAN-001",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/prada-logo-patch-wide-leg-jeans.png",
    brand: "Prada",
    shortDescription: "Jeans blu a gamba ampia con schizzi bianchi e dettagli logo sul davanti.",
    description: "Jeans cinque tasche in denim blu lavato, con gamba ampia, schizzi bianchi effetto vernice e applicazioni grafiche Prada sul davanti. Modello, composizione, taglia, codice e autenticità dovranno essere verificati sul capo prima della vendita.",
  },
  {
    id: "21000000-0000-4000-8000-000000000019",
    categoryName: "Cinture",
    categoryId: categoryIds.Cinture,
    name: "Cintura Prada in pelle con fibbia ovale incisa",
    slug: "prada-cintura-pelle-fibbia-ovale-incisa",
    sku: "PRADA-BEL-002",
    price: 0,
    currency: "EUR",
    imageUrl: "/images/catalog/prada-oval-buckle-leather-belt-black.png",
    brand: "Prada",
    shortDescription: "Cintura nera in pelle con grande fibbia ovale incisa color argento.",
    description: "Cintura in pelle nera con una fibbia ovale in metallo dall'effetto anticato, decorata con logo e motivi incisi. La linea essenziale valorizza il dettaglio frontale. Misura, larghezza e condizioni saranno confermate direttamente sul prodotto.",
  },
];

export function findPlaceholderProduct(slug: string) {
  return placeholderProducts.find((product) => product.slug === slug);
}
